import type { DatabaseConnection, DatabaseExecutor } from '@/core/database/contracts';
import type { Clock, IdGenerator } from './runtime-ports';
import type { CanonicalUnit, FoodPortion, FoodRevision, MealCategory, Nutrients, ResolutionMethod } from '@/core/domain/manual-logging';
import { ManualLoggingError, StaleReviewConflict, calculateItemNutrients, resolveQuantity, sumRequiredNutrients } from '@/core/domain/manual-logging';
import type { HistoryCursor, HistoryPage, ManualLoggingRepository, ManualLoggingWriter, MealCommand, MealDetail, PersistedItem, RequiredTotals, ReviewedItem, StoredGoal, TodaySummary } from './manual-logging-ports';
import { requireUtcTimestamp } from '@/core/time/utc-timestamp';
import { requireLocalDate } from '@/core/time/local-date';
import { MAX_SAFE_SCALED_VALUE } from '@/core/nutrition/fixed-point';

export class ValidationError extends ManualLoggingError { public constructor(message: string) { super(message); this.name = 'ValidationError'; } }
export class NotFoundError extends ManualLoggingError { public constructor(message: string) { super(message); this.name = 'NotFoundError'; } }
export class StorageError extends ManualLoggingError { public constructor(message: string) { super(message); this.name = 'StorageError'; } }

export type { MealCommand, PersistedItem, ReviewedItem } from './manual-logging-ports';
export type ManualFoodCommand = Readonly<{ name: string; basisQuantityScaled: number; basisUnit: CanonicalUnit; nutrients: Nutrients; userModified: boolean; source: FoodRevision['source'] }>;
export type PortionCommand = Readonly<{ label: string; quantityScaled: number; equivalentQuantityScaled: number; equivalentUnit: Exclude<CanonicalUnit, 'serving'> }>;
export type GoalCommand = Readonly<{ caloriesKcalScaled: number; proteinGScaled: number; carbohydratesGScaled: number; fatGScaled: number }>;

const categories: readonly MealCategory[] = ['breakfast', 'lunch', 'dinner', 'snack', 'other'];
const methods: readonly ResolutionMethod[] = ['manual', 'exact', 'alias', 'fts', 'vector', 'accepted_online'];
function requiredId(value: string | null, label: string): string {
  if (value === null || value.trim().length < 1 || value.length > 128) throw new ValidationError(`${label} is invalid.`);
  return value;
}
function validPositiveScaled(value: number): boolean { return Number.isSafeInteger(value) && value >= 1 && value <= MAX_SAFE_SCALED_VALUE; }
function validNonNegativeScaled(value: number): boolean { return Number.isSafeInteger(value) && value >= 0 && value <= MAX_SAFE_SCALED_VALUE; }
function normalizedName(value: string): string { const normalized = value.trim().toLocaleLowerCase('en-US').replace(/\s+/g, ' '); if (normalized.length < 1 || normalized.length > 256) throw new ValidationError('Food name is invalid.'); return normalized; }
function validNutrients(value: Nutrients): boolean { return validNonNegativeScaled(value.caloriesKcalScaled) && validNonNegativeScaled(value.proteinGScaled) && validNonNegativeScaled(value.carbohydratesGScaled) && validNonNegativeScaled(value.fatGScaled) && [value.fibreGScaled, value.sugarGScaled, value.sodiumMgScaled].every((optional) => optional === null || validNonNegativeScaled(optional)); }
export function validateMealCommand(command: MealCommand): void {
  if (!categories.includes(command.category)) throw new ValidationError('Meal category is invalid.');
  try { requireUtcTimestamp(command.occurredAtUtc); requireLocalDate(command.localDate); } catch { throw new ValidationError('Meal date context is invalid.'); }
  if (!Number.isInteger(command.timezoneOffsetMinutes) || command.timezoneOffsetMinutes < -720 || command.timezoneOffsetMinutes > 840) throw new ValidationError('Meal timezone offset is invalid.');
  if (command.items.length === 0) throw new ValidationError('A meal requires at least one item.');
  for (const item of command.items) {
    requiredId(item.foodId, 'Food ID'); requiredId(item.foodRevisionId, 'Food revision ID');
    if (item.inputName.trim().length < 1 || item.inputName.length > 256 || item.inputUnit.trim().length < 1 || item.inputUnit.length > 64 || !validPositiveScaled(item.inputQuantityScaled)) throw new ValidationError('Meal item input is invalid.');
    if (!methods.includes(item.resolutionMethod)) throw new ValidationError('Meal item resolution is invalid.');
    if (item.portionId !== null) requiredId(item.portionId, 'Portion ID');
  }
}
export function totalsEqual(left: Pick<Nutrients, 'caloriesKcalScaled' | 'proteinGScaled' | 'carbohydratesGScaled' | 'fatGScaled'>, right: Pick<Nutrients, 'caloriesKcalScaled' | 'proteinGScaled' | 'carbohydratesGScaled' | 'fatGScaled'>): boolean {
  return left.caloriesKcalScaled === right.caloriesKcalScaled && left.proteinGScaled === right.proteinGScaled && left.carbohydratesGScaled === right.carbohydratesGScaled && left.fatGScaled === right.fatGScaled;
}

export class ManualLoggingUseCases {
  public constructor(private readonly database: DatabaseConnection, private readonly reader: ManualLoggingRepository, private readonly writer: ManualLoggingWriter, private readonly ids: IdGenerator, private readonly clock: Clock) {}
  private async resolvedItems(transaction: DatabaseExecutor, items: readonly ReviewedItem[]): Promise<readonly PersistedItem[]> {
    const resolvedItems: PersistedItem[] = [];
    for (const [position, input] of items.entries()) {
      const foodId = requiredId(input.foodId, 'Food ID'); const revisionId = requiredId(input.foodRevisionId, 'Food revision ID');
      const revision = await this.reader.loadCurrentRevision(transaction, foodId, revisionId);
      if (revision === null) throw new StaleReviewConflict();
      const portion = input.portionId === null ? null : await this.reader.loadPortion(transaction, input.portionId);
      if (input.portionId !== null && (portion === null || portion.foodId !== foodId || portion.normalizedLabel !== input.inputUnit)) throw new StaleReviewConflict();
      const resolved = resolveQuantity(input.inputQuantityScaled, input.inputUnit, portion);
      if (resolved.unit !== revision.basisUnit) throw new StaleReviewConflict();
      resolvedItems.push({ id: requiredId(this.ids.next(), 'Generated meal item ID'), position, revision, input, resolvedQuantityScaled: resolved.quantityScaled, resolvedUnit: resolved.unit, nutrients: calculateItemNutrients(revision, resolved.quantityScaled, resolved.unit) });
    }
    return resolvedItems;
  }
  public async createMeal(command: MealCommand): Promise<string> {
    validateMealCommand(command); const id = requiredId(this.ids.next(), 'Generated ID'); let now: string; try { now = requireUtcTimestamp(this.clock.utcNow()); } catch { throw new ValidationError('Clock timestamp is invalid.'); }
    await this.database.withExclusiveTransaction(async (transaction) => { const items = await this.resolvedItems(transaction, command.items); const totals = sumRequiredNutrients(items.map((item) => item.nutrients)); this.requireOne(await this.writer.insertMeal(transaction, { id, command, totals, now })); for (const item of items) this.requireOne(await this.writer.insertMealItem(transaction, id, item, now)); const persisted = await this.writer.sumPersistedMeal(transaction, id); if (!totalsEqual(persisted, totals)) throw new StorageError('Persisted meal totals did not match.'); });
    return id;
  }
  private requireOne(result: Readonly<{ changes: number }>): void { if (result.changes !== 1) throw new StorageError('Required database row was not changed.'); }
  private requireExisting(result: Readonly<{ changes: number }>): void { if (result.changes === 0) throw new NotFoundError('Required row was not found.'); this.requireOne(result); }
  public async editMeal(mealId: string, command: MealCommand): Promise<void> { requiredId(mealId, 'Meal ID'); validateMealCommand(command); const now = this.now(); await this.database.withExclusiveTransaction(async (transaction) => { if (!await this.reader.mealExists(transaction, mealId)) throw new NotFoundError('Meal was not found.'); const items = await this.resolvedItems(transaction, command.items); const totals = sumRequiredNutrients(items.map((item) => item.nutrients)); if ((await this.writer.deleteMealItems(transaction, mealId)).changes < 1) throw new StorageError('Persisted meal has no items.'); this.requireExisting(await this.writer.updateMeal(transaction, mealId, command, totals, now)); for (const item of items) this.requireOne(await this.writer.insertMealItem(transaction, mealId, item, now)); if (!totalsEqual(await this.writer.sumPersistedMeal(transaction, mealId), totals)) throw new StorageError('Persisted meal totals did not match.'); }); }
  public async deleteMeal(mealId: string): Promise<void> { requiredId(mealId, 'Meal ID'); await this.database.withExclusiveTransaction(async (transaction) => { this.requireExisting(await this.writer.deleteMeal(transaction, mealId)); }); }
  public async replacePortion(old: FoodPortion, replacement: FoodPortion): Promise<void> { const now = this.now(); requiredId(old.id, 'Reviewed portion ID'); requiredId(replacement.id, 'Generated replacement portion ID'); if (old.foodId !== replacement.foodId || replacement.label.trim().length < 1 || replacement.normalizedLabel.trim().length < 1 || replacement.normalizedLabel !== normalizedName(replacement.label) || !validPositiveScaled(replacement.quantityScaled) || !validPositiveScaled(replacement.equivalentQuantityScaled) || !['gram', 'millilitre', 'each'].includes(replacement.equivalentUnit)) throw new ValidationError('Replacement portion is invalid.'); await this.database.withExclusiveTransaction(async (transaction) => { const reviewed = await this.reader.loadPortion(transaction, old.id); if (reviewed === null || reviewed.foodId !== old.foodId || reviewed.normalizedLabel !== old.normalizedLabel) throw new StaleReviewConflict(); this.requireOne(await this.writer.deletePortion(transaction, old.id)); this.requireOne(await this.writer.insertPortion(transaction, replacement, now)); }); }
  private now(): string { try { return requireUtcTimestamp(this.clock.utcNow()); } catch { throw new ValidationError('Clock timestamp is invalid.'); } }
  private foodRevision(foodId: string, id: string, revisionNumber: number, command: ManualFoodCommand): FoodRevision { if (command.name.trim().length < 1 || command.name.length > 256 || !validPositiveScaled(command.basisQuantityScaled) || !validNutrients(command.nutrients) || !Number.isSafeInteger(revisionNumber) || revisionNumber < 1 || !['gram', 'millilitre', 'each', 'serving'].includes(command.basisUnit) || command.userModified !== true) throw new ValidationError('Manual food is invalid.'); const source = command.source; if (source.provider !== null || source.recordId !== null || source.datasetVersion !== null || source.licenseId !== null || source.valuesHash !== null) throw new ValidationError('Manual food source is invalid.'); return { id: requiredId(id, 'Generated revision ID'), foodId, revisionNumber, basisQuantityScaled: command.basisQuantityScaled, basisUnit: command.basisUnit, nutrients: command.nutrients, userModified: command.userModified, source }; }
  public async createManualFood(command: ManualFoodCommand): Promise<string> { const id = requiredId(this.ids.next(), 'Generated food ID'); const revision = this.foodRevision(id, this.ids.next(), 1, command); const now = this.now(); const name = command.name.trim(); const normalized = normalizedName(name); await this.database.withExclusiveTransaction(async (transaction) => { this.requireOne(await this.writer.insertFood(transaction, { id, name, normalizedName: normalized, revision, now })); this.requireOne(await this.writer.insertRevision(transaction, revision, now)); }); return id; }
  public async appendFoodRevision(foodId: string, reviewedRevisionId: string, command: ManualFoodCommand): Promise<string> { requiredId(foodId, 'Food ID'); requiredId(reviewedRevisionId, 'Reviewed revision ID'); const newRevisionId = requiredId(this.ids.next(), 'Generated revision ID'); const now = this.now(); await this.database.withExclusiveTransaction(async (transaction) => { const state = await this.reader.loadFoodState(transaction, foodId); const current = await this.reader.loadCurrentRevision(transaction, foodId, reviewedRevisionId); if (state === null) throw new NotFoundError('Food was not found.'); if (state.archivedAt !== null || state.currentRevisionId !== reviewedRevisionId || current === null) throw new StaleReviewConflict(); const revision = this.foodRevision(foodId, newRevisionId, current.revisionNumber + 1, command); this.requireOne(await this.writer.insertRevision(transaction, revision, now)); this.requireOne(await this.writer.moveCurrentRevision(transaction, foodId, revision.id, now)); }); return newRevisionId; }
  public async setFoodArchived(foodId: string, archived: boolean): Promise<void> { requiredId(foodId, 'Food ID'); const now = this.now(); await this.database.withExclusiveTransaction(async (transaction) => { if (await this.reader.loadFoodState(transaction, foodId) === null) throw new NotFoundError('Food was not found.'); this.requireOne(await this.writer.setArchive(transaction, foodId, archived ? now : null, now)); }); }
  public async createPortion(foodId: string, command: PortionCommand): Promise<string> { requiredId(foodId, 'Food ID'); if (command.label.trim().length < 1 || command.label.length > 256 || !validPositiveScaled(command.quantityScaled) || !validPositiveScaled(command.equivalentQuantityScaled) || !['gram', 'millilitre', 'each'].includes(command.equivalentUnit)) throw new ValidationError('Portion is invalid.'); const id = requiredId(this.ids.next(), 'Generated portion ID'); const now = this.now(); const portion: FoodPortion = { id, foodId, label: command.label.trim(), normalizedLabel: normalizedName(command.label), quantityScaled: command.quantityScaled, equivalentQuantityScaled: command.equivalentQuantityScaled, equivalentUnit: command.equivalentUnit }; await this.database.withExclusiveTransaction(async (transaction) => { const state = await this.reader.loadFoodState(transaction, foodId); if (state === null) throw new NotFoundError('Food was not found.'); if (state.archivedAt !== null) throw new StaleReviewConflict(); this.requireOne(await this.writer.insertPortion(transaction, portion, now)); }); return id; }
  public async saveTodayGoal(command: GoalCommand): Promise<string> { if (!validPositiveScaled(command.caloriesKcalScaled) || !validNonNegativeScaled(command.proteinGScaled) || !validNonNegativeScaled(command.carbohydratesGScaled) || !validNonNegativeScaled(command.fatGScaled)) throw new ValidationError('Goal is invalid.'); let today: string; try { today = requireLocalDate(this.clock.localDate()); } catch { throw new ValidationError('Clock local date is invalid.'); } const now = this.now(); const totals: RequiredTotals = command; return this.database.withExclusiveTransaction(async (transaction) => { const existing = await this.reader.findGoal(transaction, today); if (existing !== null) { this.requireOne(await this.writer.replaceGoal(transaction, existing.id, today, totals, now)); return existing.id; } const id = requiredId(this.ids.next(), 'Generated goal ID'); this.requireOne(await this.writer.insertGoal(transaction, { id, date: today, nutrients: totals, now })); return id; }); }
  public async applicableGoal(savedLocalDate: string): Promise<StoredGoal | null> { try { requireLocalDate(savedLocalDate); } catch { throw new ValidationError('Saved local date is invalid.'); } return this.reader.findApplicableGoal(this.database, savedLocalDate); }
  public async mealDetail(mealId: string): Promise<MealDetail> { requiredId(mealId, 'Meal ID'); const detail = await this.reader.loadMealDetail(this.database, mealId); if (detail === null) throw new NotFoundError('Meal was not found.'); return detail; }
  public async today(localDate: string): Promise<TodaySummary> { try { requireLocalDate(localDate); } catch { throw new ValidationError('Today local date is invalid.'); } return this.reader.listToday(this.database, localDate); }
  public async history(limit: number, cursor: HistoryCursor | null): Promise<HistoryPage> { if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100) throw new ValidationError('History limit is invalid.'); if (cursor !== null) { try { requireUtcTimestamp(cursor.occurredAtUtc); } catch { throw new ValidationError('History cursor is invalid.'); } requiredId(cursor.id, 'History cursor ID'); } return this.reader.listHistory(this.database, limit, cursor); }
}
