import { calculateItemNutrients, resolveQuantity, sumRequiredNutrients, type FoodPortion, type FoodRevision, type Nutrients } from '@/core/domain/manual-logging';
import type { ManualFoodCommand, PortionCommand } from '@/core/application/manual-logging-use-cases';
import type { MealCommand } from '@/core/application/manual-logging-ports';
import { scaleDecimal, unscaleDecimal } from '@/core/nutrition/fixed-point';
import type { MealDraft, MealDraftItem } from './manual-logging-provider';

export type ManualFoodFields = Readonly<{ name: string; basisQuantity: string; basisUnit: string; calories: string; protein: string; carbohydrates: string; fat: string; fibre: string; sugar: string; sodium: string }>;
export type PortionFields = Readonly<{ label: string; quantity: string; equivalentQuantity: string; equivalentUnit: string }>;
export const emptyManualFoodFields: ManualFoodFields = { name: '', basisQuantity: '100', basisUnit: 'gram', calories: '', protein: '', carbohydrates: '', fat: '', fibre: '', sugar: '', sodium: '' };
export const emptyPortionFields: PortionFields = { label: '', quantity: '1', equivalentQuantity: '', equivalentUnit: 'gram' };
function isBasisUnit(value: string): value is ManualFoodCommand['basisUnit'] { return value === 'gram' || value === 'millilitre' || value === 'each' || value === 'serving'; }
function isEquivalentUnit(value: string): value is PortionCommand['equivalentUnit'] { return value === 'gram' || value === 'millilitre' || value === 'each'; }
function requiredScaled(value: string, label: string, positive: boolean): number { if (value.trim().length === 0) throw new Error(`${label} is required.`); const scaled = scaleDecimal(value.trim()); if (positive && scaled < 1) throw new Error(`${label} must be greater than zero.`); return scaled; }
function optionalScaled(value: string, label: string): number | null { return value.trim().length === 0 ? null : requiredScaled(value, label, false); }
function positiveScaled(value: string, label: string): number { return requiredScaled(value, label, true); }
export function toManualFoodCommand(fields: ManualFoodFields): ManualFoodCommand { if (!isBasisUnit(fields.basisUnit)) throw new Error('Basis unit must be gram, millilitre, each, or serving.'); const nutrients: Nutrients = { caloriesKcalScaled: requiredScaled(fields.calories, 'Calories', false), proteinGScaled: requiredScaled(fields.protein, 'Protein', false), carbohydratesGScaled: requiredScaled(fields.carbohydrates, 'Carbohydrates', false), fatGScaled: requiredScaled(fields.fat, 'Fat', false), fibreGScaled: optionalScaled(fields.fibre, 'Fibre'), sugarGScaled: optionalScaled(fields.sugar, 'Sugar'), sodiumMgScaled: optionalScaled(fields.sodium, 'Sodium') }; return { name: fields.name, basisQuantityScaled: positiveScaled(fields.basisQuantity, 'Basis quantity'), basisUnit: fields.basisUnit, nutrients, userModified: true, source: { provider: null, recordId: null, datasetVersion: null, licenseId: null, valuesHash: null } }; }
export function toPortionCommand(fields: PortionFields): PortionCommand { if (!isEquivalentUnit(fields.equivalentUnit)) throw new Error('Equivalent unit must be gram, millilitre, or each.'); return { label: fields.label, quantityScaled: positiveScaled(fields.quantity, 'Portion quantity'), equivalentQuantityScaled: positiveScaled(fields.equivalentQuantity, 'Equivalent quantity'), equivalentUnit: fields.equivalentUnit }; }
export function fieldsFromRevision(name: string, revision: Readonly<{ basisQuantityScaled: number; basisUnit: string; nutrients: Nutrients }>): ManualFoodFields { const n = revision.nutrients; return { name, basisQuantity: unscaleDecimal(revision.basisQuantityScaled), basisUnit: revision.basisUnit, calories: unscaleDecimal(n.caloriesKcalScaled), protein: unscaleDecimal(n.proteinGScaled), carbohydrates: unscaleDecimal(n.carbohydratesGScaled), fat: unscaleDecimal(n.fatGScaled), fibre: n.fibreGScaled === null ? '' : unscaleDecimal(n.fibreGScaled), sugar: n.sugarGScaled === null ? '' : unscaleDecimal(n.sugarGScaled), sodium: n.sodiumMgScaled === null ? '' : unscaleDecimal(n.sodiumMgScaled) }; }
export function toMealCommand(draft: MealDraft): MealCommand { if (draft.items.some((item) => item.requiresReview)) throw new Error('Resolve every flagged meal item before saving.'); return { category: draft.category, occurredAtUtc: draft.occurredAtUtc, localDate: draft.localDate, timezoneOffsetMinutes: draft.timezoneOffsetMinutes, items: draft.items.map((item) => ({ foodId: item.foodId, foodRevisionId: item.foodRevisionId, portionId: item.portionId, inputName: item.canonicalName, inputQuantityScaled: positiveScaled(item.inputQuantity, `Quantity for ${item.canonicalName}`), inputUnit: item.inputUnit.trim().toLocaleLowerCase('en-US'), resolutionMethod: item.resolutionMethod ?? 'manual' })) }; }
export type MealPreviewItem = Readonly<{ id: string; nutrients: Nutrients }>;
export type MealPreview = Readonly<{ items: readonly MealPreviewItem[]; totals: Readonly<Pick<Nutrients, 'caloriesKcalScaled' | 'proteinGScaled' | 'carbohydratesGScaled' | 'fatGScaled'>> }>;
export type PreviewResolution = Readonly<{ item: MealDraftItem; revision: FoodRevision; portion: FoodPortion | null }>;
export function previewMeal(resolutions: readonly PreviewResolution[]): MealPreview { const items = resolutions.map(({ item, portion, revision }) => { if (item.requiresReview) throw new Error(`${item.canonicalName} requires review.`); if (portion !== null && portion.id !== item.portionId) throw new Error(`${item.canonicalName} portion is no longer current.`); const quantity = resolveQuantity(positiveScaled(item.inputQuantity, `Quantity for ${item.canonicalName}`), item.inputUnit.trim().toLocaleLowerCase('en-US'), portion); if (quantity.unit !== revision.basisUnit) throw new Error(`${item.canonicalName} has an incompatible unit.`); return { id: item.id, nutrients: calculateItemNutrients(revision, quantity.quantityScaled, quantity.unit) }; }); return { items, totals: sumRequiredNutrients(items.map((item) => item.nutrients)) }; }
